# Generated by Django 5.0.6 on 2024-07-06 05:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomeUser_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('User_Type', models.CharField(choices=[('recruiter', 'Recruiter'), ('jobseeker', 'Jobseeker')], max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100, null=True)),
                ('Profile_Picture', models.ImageField(null=True, upload_to='media/profilepicture')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=100, null=True)),
                ('Designation', models.CharField(max_length=100, null=True)),
                ('Duration', models.CharField(max_length=100, null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('seekeruser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workexinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationQualifiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=100, null=True)),
                ('Passing_Year', models.CharField(max_length=100, null=True)),
                ('Grade', models.CharField(max_length=100, null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('seekeruser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eduinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobil_Number', models.CharField(max_length=100, null=True)),
                ('Emergency_Contact', models.CharField(max_length=100, null=True)),
                ('Present_Address', models.CharField(max_length=100, null=True)),
                ('Permanent_Address', models.CharField(max_length=100, null=True)),
                ('portaluser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasicInformation_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faters_Name', models.CharField(max_length=100, null=True)),
                ('Mothers_Name', models.CharField(max_length=100, null=True)),
                ('Marital_Status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=100, null=True)),
                ('Date_Of_Birth', models.DateField(null=True)),
                ('portaluser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basicinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddJob_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Title', models.CharField(max_length=100, null=True)),
                ('Company_Name', models.CharField(max_length=100, null=True)),
                ('Company_Description', models.TextField(null=True)),
                ('Company_Logo', models.ImageField(null=True, upload_to='media/logo')),
                ('Company_Location', models.CharField(max_length=200, null=True)),
                ('Qualifications', models.CharField(max_length=100, null=True)),
                ('Dead_Line', models.DateField(null=True)),
                ('Salary', models.CharField(max_length=100, null=True)),
                ('recruiteruser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
