# Generated by Django 5.0.6 on 2024-07-06 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applyjob_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skills', models.CharField(max_length=100, null=True)),
                ('Resume', models.FileField(null=True, upload_to='media/resume')),
                ('Seeker_Profile_Pic', models.ImageField(null=True, upload_to='media/image')),
                ('Status', models.CharField(default='Pending', max_length=200, null=True)),
                ('Applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applyjob', to=settings.AUTH_USER_MODEL)),
                ('Applied_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobApp.addjob_model')),
            ],
        ),
    ]
